* var+prm-init.inc

* endogenous variables
CPI.L       = CPI0;
EG.L        = EG0;
EXR.L       = EXR0;
KD.L(a)     = KD0(a);
KS.L        = KS0;
LD.L(a)     = LD0(a);
LS.L        = LS0;
PA.L(a)     = PA0(a);
PD.L(c)     = PD0(c);
PE.L(c)     = PE0(c);
PM.L(c)     = PM0(c);
PQ.L(c)     = PQ0(c);
PVA.L(a)    = PVA0(a);
PX.L(c)     = PX0(c);
QA.L(a)     = QA0(a);
QD.L(c)     = QD0(c);
QE.L(c)     = QE0(c);
QH.L(c)     = QH0(c);
QINT.L(c,a) = QINT0(c,a);
QINV.L(c)   = QINV0(c);
QINVSCAL.L  = QINVSCAL0;
QM.L(c)     = QM0(c);
QQ.L(c)     = QQ0(c);
QX.L(c)     = QX0(c);
WALRAS.L    = 0;
WK.L(a)     = WK0(a);
WL.L        = WL0;
YG.L        = YG0;
YH.L        = YH0;
YK.L        = YK0;
YL.L        = YL0;

* exogenous variables and parameters
pwe(c) = pwe0(c);
pwm(c) = pwm0(c);

tq(c) = tq0(c);
tm(c) = tm0(c);
qg(c) = qg0(c);