%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'dmp_2c_xu';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('dmp_2c_xu.log');
M_.exo_names = 'epsiaa';
M_.exo_names_tex = 'epsiaa';
M_.exo_names_long = 'epsiaa';
M_.exo_names = char(M_.exo_names, 'epsibb');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsibb');
M_.exo_names_long = char(M_.exo_names_long, 'epsibb');
M_.endo_names = 'V1t';
M_.endo_names_tex = 'V1t';
M_.endo_names_long = 'V1t';
M_.endo_names = char(M_.endo_names, 'V2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'V2t');
M_.endo_names_long = char(M_.endo_names_long, 'V2t');
M_.endo_names = char(M_.endo_names, 'Kc1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kc1t');
M_.endo_names_long = char(M_.endo_names_long, 'Kc1t');
M_.endo_names = char(M_.endo_names, 'Kc2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kc2t');
M_.endo_names_long = char(M_.endo_names_long, 'Kc2t');
M_.endo_names = char(M_.endo_names, 'N1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'N1t');
M_.endo_names_long = char(M_.endo_names_long, 'N1t');
M_.endo_names = char(M_.endo_names, 'N2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'N2t');
M_.endo_names_long = char(M_.endo_names_long, 'N2t');
M_.endo_names = char(M_.endo_names, 'Y1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y1t');
M_.endo_names_long = char(M_.endo_names_long, 'Y1t');
M_.endo_names = char(M_.endo_names, 'Y2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y2t');
M_.endo_names_long = char(M_.endo_names_long, 'Y2t');
M_.endo_names = char(M_.endo_names, 'Cc1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cc1t');
M_.endo_names_long = char(M_.endo_names_long, 'Cc1t');
M_.endo_names = char(M_.endo_names, 'Cc2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cc2t');
M_.endo_names_long = char(M_.endo_names_long, 'Cc2t');
M_.endo_names = char(M_.endo_names, 'lambda1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda1t');
M_.endo_names_long = char(M_.endo_names_long, 'lambda1t');
M_.endo_names = char(M_.endo_names, 'lambda2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda2t');
M_.endo_names_long = char(M_.endo_names_long, 'lambda2t');
M_.endo_names = char(M_.endo_names, 'Pc1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pc1t');
M_.endo_names_long = char(M_.endo_names_long, 'Pc1t');
M_.endo_names = char(M_.endo_names, 'Pc2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pc2t');
M_.endo_names_long = char(M_.endo_names_long, 'Pc2t');
M_.endo_names = char(M_.endo_names, 'h1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'h1t');
M_.endo_names_long = char(M_.endo_names_long, 'h1t');
M_.endo_names = char(M_.endo_names, 'h2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'h2t');
M_.endo_names_long = char(M_.endo_names_long, 'h2t');
M_.endo_names = char(M_.endo_names, 'W1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'W1t');
M_.endo_names_long = char(M_.endo_names_long, 'W1t');
M_.endo_names = char(M_.endo_names, 'W2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'W2t');
M_.endo_names_long = char(M_.endo_names_long, 'W2t');
M_.endo_names = char(M_.endo_names, 'P1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'P1t');
M_.endo_names_long = char(M_.endo_names_long, 'P1t');
M_.endo_names = char(M_.endo_names, 'P2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'P2t');
M_.endo_names_long = char(M_.endo_names_long, 'P2t');
M_.endo_names = char(M_.endo_names, 'mu1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu1t');
M_.endo_names_long = char(M_.endo_names_long, 'mu1t');
M_.endo_names = char(M_.endo_names, 'mu2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu2t');
M_.endo_names_long = char(M_.endo_names_long, 'mu2t');
M_.endo_names = char(M_.endo_names, 'xi1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi1t');
M_.endo_names_long = char(M_.endo_names_long, 'xi1t');
M_.endo_names = char(M_.endo_names, 'xi2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'xi2t');
M_.endo_names_long = char(M_.endo_names_long, 'xi2t');
M_.endo_names = char(M_.endo_names, 'm1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'm1t');
M_.endo_names_long = char(M_.endo_names_long, 'm1t');
M_.endo_names = char(M_.endo_names, 'm2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'm2t');
M_.endo_names_long = char(M_.endo_names_long, 'm2t');
M_.endo_names = char(M_.endo_names, 'q1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'q1t');
M_.endo_names_long = char(M_.endo_names_long, 'q1t');
M_.endo_names = char(M_.endo_names, 'q2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'q2t');
M_.endo_names_long = char(M_.endo_names_long, 'q2t');
M_.endo_names = char(M_.endo_names, 'Ic1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ic1t');
M_.endo_names_long = char(M_.endo_names_long, 'Ic1t');
M_.endo_names = char(M_.endo_names, 'Ic2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ic2t');
M_.endo_names_long = char(M_.endo_names_long, 'Ic2t');
M_.endo_names = char(M_.endo_names, 'Yb1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yb1t');
M_.endo_names_long = char(M_.endo_names_long, 'Yb1t');
M_.endo_names = char(M_.endo_names, 'Yb2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yb2t');
M_.endo_names_long = char(M_.endo_names_long, 'Yb2t');
M_.endo_names = char(M_.endo_names, 'lnV1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnV1t');
M_.endo_names_long = char(M_.endo_names_long, 'lnV1t');
M_.endo_names = char(M_.endo_names, 'lnV2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnV2t');
M_.endo_names_long = char(M_.endo_names_long, 'lnV2t');
M_.endo_names = char(M_.endo_names, 'a1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'a1t');
M_.endo_names_long = char(M_.endo_names_long, 'a1t');
M_.endo_names = char(M_.endo_names, 'a2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'a2t');
M_.endo_names_long = char(M_.endo_names_long, 'a2t');
M_.endo_names = char(M_.endo_names, 'LabProd1');
M_.endo_names_tex = char(M_.endo_names_tex, 'LabProd1');
M_.endo_names_long = char(M_.endo_names_long, 'LabProd1');
M_.endo_names = char(M_.endo_names, 'LabProd2');
M_.endo_names_tex = char(M_.endo_names_tex, 'LabProd2');
M_.endo_names_long = char(M_.endo_names_long, 'LabProd2');
M_.endo_names = char(M_.endo_names, 'TotHours1');
M_.endo_names_tex = char(M_.endo_names_tex, 'TotHours1');
M_.endo_names_long = char(M_.endo_names_long, 'TotHours1');
M_.endo_names = char(M_.endo_names, 'TotHours2');
M_.endo_names_tex = char(M_.endo_names_tex, 'TotHours2');
M_.endo_names_long = char(M_.endo_names_long, 'TotHours2');
M_.endo_names = char(M_.endo_names, 'lnTotHours1');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnTotHours1');
M_.endo_names_long = char(M_.endo_names_long, 'lnTotHours1');
M_.endo_names = char(M_.endo_names, 'lnTotHours2');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnTotHours2');
M_.endo_names_long = char(M_.endo_names_long, 'lnTotHours2');
M_.endo_names = char(M_.endo_names, 'LabShare1');
M_.endo_names_tex = char(M_.endo_names_tex, 'LabShare1');
M_.endo_names_long = char(M_.endo_names_long, 'LabShare1');
M_.endo_names = char(M_.endo_names, 'LabShare2');
M_.endo_names_tex = char(M_.endo_names_tex, 'LabShare2');
M_.endo_names_long = char(M_.endo_names_long, 'LabShare2');
M_.endo_names = char(M_.endo_names, 'lnYb1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnYb1t');
M_.endo_names_long = char(M_.endo_names_long, 'lnYb1t');
M_.endo_names = char(M_.endo_names, 'lnYb2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnYb2t');
M_.endo_names_long = char(M_.endo_names_long, 'lnYb2t');
M_.endo_names = char(M_.endo_names, 'lnN1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnN1t');
M_.endo_names_long = char(M_.endo_names_long, 'lnN1t');
M_.endo_names = char(M_.endo_names, 'lnN2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnN2t');
M_.endo_names_long = char(M_.endo_names_long, 'lnN2t');
M_.endo_names = char(M_.endo_names, 'lnIc1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnIc1t');
M_.endo_names_long = char(M_.endo_names_long, 'lnIc1t');
M_.endo_names = char(M_.endo_names, 'lnIc2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnIc2t');
M_.endo_names_long = char(M_.endo_names_long, 'lnIc2t');
M_.endo_names = char(M_.endo_names, 'lnCc1t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnCc1t');
M_.endo_names_long = char(M_.endo_names_long, 'lnCc1t');
M_.endo_names = char(M_.endo_names, 'lnCc2t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnCc2t');
M_.endo_names_long = char(M_.endo_names_long, 'lnCc2t');
M_.endo_partitions = struct();
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'Phi');
M_.param_names_tex = char(M_.param_names_tex, 'Phi');
M_.param_names_long = char(M_.param_names_long, 'Phi');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'A1');
M_.param_names_tex = char(M_.param_names_tex, 'A1');
M_.param_names_long = char(M_.param_names_long, 'A1');
M_.param_names = char(M_.param_names, 'A2');
M_.param_names_tex = char(M_.param_names_tex, 'A2');
M_.param_names_long = char(M_.param_names_long, 'A2');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoas');
M_.param_names_tex = char(M_.param_names_tex, 'rhoas');
M_.param_names_long = char(M_.param_names_long, 'rhoas');
M_.param_names = char(M_.param_names, 'sigmaa');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaa');
M_.param_names_long = char(M_.param_names_long, 'sigmaa');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'omega1V1sY1');
M_.param_names_tex = char(M_.param_names_tex, 'omega1V1sY1');
M_.param_names_long = char(M_.param_names_long, 'omega1V1sY1');
M_.param_names = char(M_.param_names, 'omega2V2sY2');
M_.param_names_tex = char(M_.param_names_tex, 'omega2V2sY2');
M_.param_names_long = char(M_.param_names_long, 'omega2V2sY2');
M_.param_names = char(M_.param_names, 'N1s');
M_.param_names_tex = char(M_.param_names_tex, 'N1s');
M_.param_names_long = char(M_.param_names_long, 'N1s');
M_.param_names = char(M_.param_names, 'N2s');
M_.param_names_tex = char(M_.param_names_tex, 'N2s');
M_.param_names_long = char(M_.param_names_long, 'N2s');
M_.param_names = char(M_.param_names, 'e1');
M_.param_names_tex = char(M_.param_names_tex, 'e1');
M_.param_names_long = char(M_.param_names_long, 'e1');
M_.param_names = char(M_.param_names, 'm1s');
M_.param_names_tex = char(M_.param_names_tex, 'm1s');
M_.param_names_long = char(M_.param_names_long, 'm1s');
M_.param_names = char(M_.param_names, 'h2s');
M_.param_names_tex = char(M_.param_names_tex, 'h2s');
M_.param_names_long = char(M_.param_names_long, 'h2s');
M_.param_names = char(M_.param_names, 'e2');
M_.param_names_tex = char(M_.param_names_tex, 'e2');
M_.param_names_long = char(M_.param_names_long, 'e2');
M_.param_names = char(M_.param_names, 'm2s');
M_.param_names_tex = char(M_.param_names_tex, 'm2s');
M_.param_names_long = char(M_.param_names_long, 'm2s');
M_.param_names = char(M_.param_names, 'V1s');
M_.param_names_tex = char(M_.param_names_tex, 'V1s');
M_.param_names_long = char(M_.param_names_long, 'V1s');
M_.param_names = char(M_.param_names, 'V2s');
M_.param_names_tex = char(M_.param_names_tex, 'V2s');
M_.param_names_long = char(M_.param_names_long, 'V2s');
M_.param_names = char(M_.param_names, 'mu1s');
M_.param_names_tex = char(M_.param_names_tex, 'mu1s');
M_.param_names_long = char(M_.param_names_long, 'mu1s');
M_.param_names = char(M_.param_names, 'mu2s');
M_.param_names_tex = char(M_.param_names_tex, 'mu2s');
M_.param_names_long = char(M_.param_names_long, 'mu2s');
M_.param_names = char(M_.param_names, 'Xi');
M_.param_names_tex = char(M_.param_names_tex, 'Xi');
M_.param_names_long = char(M_.param_names_long, 'Xi');
M_.param_names = char(M_.param_names, 'P1s');
M_.param_names_tex = char(M_.param_names_tex, 'P1s');
M_.param_names_long = char(M_.param_names_long, 'P1s');
M_.param_names = char(M_.param_names, 'P2s');
M_.param_names_tex = char(M_.param_names_tex, 'P2s');
M_.param_names_long = char(M_.param_names_long, 'P2s');
M_.param_names = char(M_.param_names, 'Pc1s');
M_.param_names_tex = char(M_.param_names_tex, 'Pc1s');
M_.param_names_long = char(M_.param_names_long, 'Pc1s');
M_.param_names = char(M_.param_names, 'Pc2s');
M_.param_names_tex = char(M_.param_names_tex, 'Pc2s');
M_.param_names_long = char(M_.param_names_long, 'Pc2s');
M_.param_names = char(M_.param_names, 'Y1sKc1');
M_.param_names_tex = char(M_.param_names_tex, 'Y1sKc1');
M_.param_names_long = char(M_.param_names_long, 'Y1sKc1');
M_.param_names = char(M_.param_names, 'Kc1s');
M_.param_names_tex = char(M_.param_names_tex, 'Kc1s');
M_.param_names_long = char(M_.param_names_long, 'Kc1s');
M_.param_names = char(M_.param_names, 'Y1s');
M_.param_names_tex = char(M_.param_names_tex, 'Y1s');
M_.param_names_long = char(M_.param_names_long, 'Y1s');
M_.param_names = char(M_.param_names, 'Y2sKc2');
M_.param_names_tex = char(M_.param_names_tex, 'Y2sKc2');
M_.param_names_long = char(M_.param_names_long, 'Y2sKc2');
M_.param_names = char(M_.param_names, 'Kc2sh2N2');
M_.param_names_tex = char(M_.param_names_tex, 'Kc2sh2N2');
M_.param_names_long = char(M_.param_names_long, 'Kc2sh2N2');
M_.param_names = char(M_.param_names, 'Kc2s');
M_.param_names_tex = char(M_.param_names_tex, 'Kc2s');
M_.param_names_long = char(M_.param_names_long, 'Kc2s');
M_.param_names = char(M_.param_names, 'Y2s');
M_.param_names_tex = char(M_.param_names_tex, 'Y2s');
M_.param_names_long = char(M_.param_names_long, 'Y2s');
M_.param_names = char(M_.param_names, 'Ic1s');
M_.param_names_tex = char(M_.param_names_tex, 'Ic1s');
M_.param_names_long = char(M_.param_names_long, 'Ic1s');
M_.param_names = char(M_.param_names, 'Ic2s');
M_.param_names_tex = char(M_.param_names_tex, 'Ic2s');
M_.param_names_long = char(M_.param_names_long, 'Ic2s');
M_.param_names = char(M_.param_names, 'omega1');
M_.param_names_tex = char(M_.param_names_tex, 'omega1');
M_.param_names_long = char(M_.param_names_long, 'omega1');
M_.param_names = char(M_.param_names, 'omega2');
M_.param_names_tex = char(M_.param_names_tex, 'omega2');
M_.param_names_long = char(M_.param_names_long, 'omega2');
M_.param_names = char(M_.param_names, 'Yb1s');
M_.param_names_tex = char(M_.param_names_tex, 'Yb1s');
M_.param_names_long = char(M_.param_names_long, 'Yb1s');
M_.param_names = char(M_.param_names, 'Yb2s');
M_.param_names_tex = char(M_.param_names_tex, 'Yb2s');
M_.param_names_long = char(M_.param_names_long, 'Yb2s');
M_.param_names = char(M_.param_names, 'Cc1s');
M_.param_names_tex = char(M_.param_names_tex, 'Cc1s');
M_.param_names_long = char(M_.param_names_long, 'Cc1s');
M_.param_names = char(M_.param_names, 'Cc2s');
M_.param_names_tex = char(M_.param_names_tex, 'Cc2s');
M_.param_names_long = char(M_.param_names_long, 'Cc2s');
M_.param_names = char(M_.param_names, 'lambda1s');
M_.param_names_tex = char(M_.param_names_tex, 'lambda1s');
M_.param_names_long = char(M_.param_names_long, 'lambda1s');
M_.param_names = char(M_.param_names, 'lambda2s');
M_.param_names_tex = char(M_.param_names_tex, 'lambda2s');
M_.param_names_long = char(M_.param_names_long, 'lambda2s');
M_.param_names = char(M_.param_names, 'sigman');
M_.param_names_tex = char(M_.param_names_tex, 'sigman');
M_.param_names_long = char(M_.param_names_long, 'sigman');
M_.param_names = char(M_.param_names, 'xi1s');
M_.param_names_tex = char(M_.param_names_tex, 'xi1s');
M_.param_names_long = char(M_.param_names_long, 'xi1s');
M_.param_names = char(M_.param_names, 'xi2s');
M_.param_names_tex = char(M_.param_names_tex, 'xi2s');
M_.param_names_long = char(M_.param_names_long, 'xi2s');
M_.param_names = char(M_.param_names, 'W1s');
M_.param_names_tex = char(M_.param_names_tex, 'W1s');
M_.param_names_long = char(M_.param_names_long, 'W1s');
M_.param_names = char(M_.param_names, 'W2s');
M_.param_names_tex = char(M_.param_names_tex, 'W2s');
M_.param_names_long = char(M_.param_names_long, 'W2s');
M_.param_names = char(M_.param_names, 'sigmau');
M_.param_names_tex = char(M_.param_names_tex, 'sigmau');
M_.param_names_long = char(M_.param_names_long, 'sigmau');
M_.param_names = char(M_.param_names, 'q2s');
M_.param_names_tex = char(M_.param_names_tex, 'q2s');
M_.param_names_long = char(M_.param_names_long, 'q2s');
M_.param_names = char(M_.param_names, 'gg');
M_.param_names_tex = char(M_.param_names_tex, 'gg');
M_.param_names_long = char(M_.param_names_long, 'gg');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 52;
M_.param_nbr = 59;
M_.orig_endo_nbr = 52;
M_.aux_vars = [];
M_.predetermined_variables = [ 3 4 5 6 ];
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('dmp_2c_xu_static');
erase_compiled_function('dmp_2c_xu_dynamic');
M_.orig_eq_nbr = 52;
M_.eq_nbr = 52;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 7 0;
 0 8 0;
 1 9 0;
 2 10 0;
 3 11 0;
 4 12 0;
 0 13 59;
 0 14 60;
 0 15 0;
 0 16 0;
 0 17 61;
 0 18 62;
 0 19 0;
 0 20 0;
 0 21 63;
 0 22 64;
 0 23 65;
 0 24 66;
 0 25 67;
 0 26 68;
 0 27 0;
 0 28 0;
 0 29 69;
 0 30 70;
 0 31 0;
 0 32 0;
 0 33 71;
 0 34 72;
 0 35 73;
 0 36 74;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 5 41 0;
 6 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;]';
M_.nstatic = 30;
M_.nfwrd   = 16;
M_.npred   = 6;
M_.nboth   = 0;
M_.nsfwrd   = 16;
M_.nspred   = 6;
M_.ndynamic   = 22;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(52, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(59, 1);
M_.NNZDerivatives = [207; -1; -1];
close all;
M_.params( 1 ) = 0.99;
beta = M_.params( 1 );
M_.params( 2 ) = 5;
eta = M_.params( 2 );
M_.params( 3 ) = 0.85;
gamma = M_.params( 3 );
M_.params( 4 ) = 1.5;
theta = M_.params( 4 );
M_.params( 5 ) = 0.65;
alpha = M_.params( 5 );
M_.params( 6 ) = 0.025;
delta = M_.params( 6 );
M_.params( 7 ) = 0.1;
s = M_.params( 7 );
M_.params( 8 ) = 1.63;
Phi = M_.params( 8 );
M_.params( 9 ) = 0.6;
epsilon = M_.params( 9 );
M_.params( 10 ) = M_.params(9);
phi = M_.params( 10 );
M_.params( 11 ) = 1;
A1 = M_.params( 11 );
M_.params( 12 ) = 1;
A2 = M_.params( 12 );
M_.params( 13 ) = 0.906;
rhoa = M_.params( 13 );
M_.params( 14 ) = 0.088;
rhoas = M_.params( 14 );
M_.params( 15 ) = 0.00852;
sigmaa = M_.params( 15 );
M_.params( 16 ) = 0.133;
psi = M_.params( 16 );
M_.params( 17 ) = 0.01;
omega1V1sY1 = M_.params( 17 );
M_.params( 18 ) = 0.01;
omega2V2sY2 = M_.params( 18 );
M_.params( 19 ) = 0.57;
N1s = M_.params( 19 );
h1s=1/3;
M_.params( 21 ) = 0.5*h1s;
e1 = M_.params( 21 );
M_.params( 22 ) = 0.90;
m1s = M_.params( 22 );
M_.params( 20 ) = 0.57;
N2s = M_.params( 20 );
M_.params( 23 ) = 0.3333333333333333;
h2s = M_.params( 23 );
M_.params( 24 ) = 0.5*M_.params(23);
e2 = M_.params( 24 );
M_.params( 25 ) = 0.90;
m2s = M_.params( 25 );
M_.params( 26 ) = M_.params(7)*M_.params(19)/M_.params(22);
V1s = M_.params( 26 );
M_.params( 27 ) = M_.params(7)*M_.params(20)/M_.params(25);
V2s = M_.params( 27 );
M_.params( 28 ) = M_.params(26)/(M_.params(21)*(1-M_.params(19)));
mu1s = M_.params( 28 );
M_.params( 29 ) = M_.params(27)/(M_.params(24)*(1-M_.params(20)));
mu2s = M_.params( 29 );
M_.params( 30 ) = M_.params(22)/M_.params(28)^(M_.params(10)-1);
Xi = M_.params( 30 );
M_.params( 31 ) = 1;
P1s = M_.params( 31 );
M_.params( 32 ) = 1;
P2s = M_.params( 32 );
M_.params( 33 ) = 1;
Pc1s = M_.params( 33 );
M_.params( 34 ) = 1;
Pc2s = M_.params( 34 );
M_.params( 35 ) = (1/M_.params(1)-(1-M_.params(6)))/(1-M_.params(5));
Y1sKc1 = M_.params( 35 );
Kc1sh1N1=(1/A1*Y1sKc1)^(-1/alpha);
M_.params( 36 ) = M_.params(19)*h1s*Kc1sh1N1;
Kc1s = M_.params( 36 );
M_.params( 37 ) = M_.params(35)*M_.params(36);
Y1s = M_.params( 37 );
M_.params( 38 ) = (1/M_.params(1)-(1-M_.params(6)))/(1-M_.params(5));
Y2sKc2 = M_.params( 38 );
M_.params( 39 ) = (1/M_.params(12)*M_.params(38))^((-1)/M_.params(5));
Kc2sh2N2 = M_.params( 39 );
M_.params( 40 ) = M_.params(20)*M_.params(23)*M_.params(39);
Kc2s = M_.params( 40 );
M_.params( 41 ) = M_.params(38)*M_.params(40);
Y2s = M_.params( 41 );
M_.params( 42 ) = M_.params(6)*M_.params(36);
Ic1s = M_.params( 42 );
M_.params( 43 ) = M_.params(6)*M_.params(40);
Ic2s = M_.params( 43 );
M_.params( 44 ) = M_.params(17)*M_.params(37)/M_.params(26);
omega1 = M_.params( 44 );
M_.params( 45 ) = M_.params(18)*M_.params(41)/M_.params(27);
omega2 = M_.params( 45 );
M_.params( 46 ) = M_.params(37)-M_.params(26)*M_.params(44);
Yb1s = M_.params( 46 );
M_.params( 47 ) = M_.params(41)-M_.params(27)*M_.params(45);
Yb2s = M_.params( 47 );
M_.params( 48 ) = M_.params(46)-M_.params(42);
Cc1s = M_.params( 48 );
M_.params( 49 ) = M_.params(47)-M_.params(43);
Cc2s = M_.params( 49 );
M_.params( 50 ) = 1/(M_.params(48)*M_.params(33));
lambda1s = M_.params( 50 );
M_.params( 51 ) = 1/(M_.params(49)*M_.params(34));
lambda2s = M_.params( 51 );
M_.params( 52 ) = M_.params(5)*M_.params(37)/(h1s*M_.params(19))*M_.params(31)*M_.params(50)/(1-h1s)^(-M_.params(2));
sigman = M_.params( 52 );
M_.params( 53 ) = M_.params(44)*M_.params(31)/M_.params(22);
xi1s = M_.params( 53 );
M_.params( 54 ) = M_.params(45)*M_.params(32)/M_.params(25);
xi2s = M_.params( 54 );
M_.params( 55 ) = ((1-M_.params(7))*M_.params(53)-M_.params(53)/M_.params(1)+h1s*M_.params(37)*M_.params(5)*M_.params(31)/(h1s*M_.params(19)))/h1s;
W1s = M_.params( 55 );
M_.params( 56 ) = ((1-M_.params(7))*M_.params(54)-M_.params(54)/M_.params(1)+M_.params(23)*M_.params(41)*M_.params(5)*M_.params(32)/(M_.params(23)*M_.params(20)))/M_.params(23);
W2s = M_.params( 56 );
M_.params( 57 ) = (1-M_.params(2))*(h1s*M_.params(50)*M_.params(55)-M_.params(50)*(1-M_.params(9))*(h1s*M_.params(37)*M_.params(5)*M_.params(31)/(h1s*M_.params(19))+M_.params(44)*M_.params(28)*M_.params(21)*M_.params(31))+M_.params(9)*M_.params(52)*(1-h1s)^(1-M_.params(2))/(1-M_.params(2)))/(M_.params(9)*(1-M_.params(21))^(1-M_.params(2)));
sigmau = M_.params( 57 );
q1s=Pc1s;
M_.params( 58 ) = M_.params(34);
q2s = M_.params( 58 );
M_.params( 59 ) = 0.133;
gg = M_.params( 59 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 3 ) = M_.params(36);
oo_.steady_state( 5 ) = M_.params(19);
oo_.steady_state( 7 ) = M_.params(37);
oo_.steady_state( 9 ) = M_.params(48);
oo_.steady_state( 11 ) = M_.params(50);
oo_.steady_state( 13 ) = M_.params(33);
oo_.steady_state( 15 ) = h1s;
oo_.steady_state( 17 ) = M_.params(55);
oo_.steady_state( 19 ) = M_.params(31);
oo_.steady_state( 21 ) = M_.params(28);
oo_.steady_state( 23 ) = M_.params(53);
oo_.steady_state( 25 ) = M_.params(22);
oo_.steady_state( 27 ) = q1s;
oo_.steady_state( 29 ) = M_.params(42);
oo_.steady_state( 1 ) = M_.params(26);
oo_.steady_state( 31 ) = M_.params(46);
oo_.steady_state( 4 ) = M_.params(40);
oo_.steady_state( 6 ) = M_.params(20);
oo_.steady_state( 8 ) = M_.params(41);
oo_.steady_state( 10 ) = M_.params(49);
oo_.steady_state( 12 ) = M_.params(51);
oo_.steady_state( 14 ) = M_.params(34);
oo_.steady_state( 16 ) = M_.params(23);
oo_.steady_state( 18 ) = M_.params(56);
oo_.steady_state( 20 ) = M_.params(32);
oo_.steady_state( 22 ) = M_.params(29);
oo_.steady_state( 24 ) = M_.params(54);
oo_.steady_state( 26 ) = M_.params(25);
oo_.steady_state( 28 ) = M_.params(58);
oo_.steady_state( 30 ) = M_.params(43);
oo_.steady_state( 2 ) = M_.params(27);
oo_.steady_state( 32 ) = M_.params(47);
oo_.steady_state( 37 ) = M_.params(37)/(h1s*M_.params(19));
oo_.steady_state( 43 ) = M_.params(19)*h1s*M_.params(55)/M_.params(37);
oo_.steady_state( 39 ) = h1s*M_.params(19);
oo_.steady_state( 38 ) = M_.params(41)/(M_.params(23)*M_.params(20));
oo_.steady_state( 44 ) = M_.params(20)*M_.params(23)*M_.params(56)/M_.params(41);
oo_.steady_state( 40 ) = M_.params(23)*M_.params(20);
oo_.steady_state( 45 ) = log(oo_.steady_state(31));
oo_.steady_state( 46 ) = log(oo_.steady_state(32));
oo_.steady_state( 47 ) = log(oo_.steady_state(5));
oo_.steady_state( 48 ) = log(oo_.steady_state(6));
oo_.steady_state( 49 ) = log(oo_.steady_state(29));
oo_.steady_state( 50 ) = log(oo_.steady_state(30));
oo_.steady_state( 51 ) = log(oo_.steady_state(9));
oo_.steady_state( 52 ) = log(oo_.steady_state(10));
oo_.steady_state( 33 ) = log(oo_.steady_state(1));
oo_.steady_state( 34 ) = log(oo_.steady_state(2));
oo_.steady_state( 41 ) = log(oo_.steady_state(39));
oo_.steady_state( 42 ) = log(oo_.steady_state(40));
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 7.25904e-005;
M_.Sigma_e(2, 2) = 7.25904e-005;
resid
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.hp_filter = 1600;
options_.irf = 40;
options_.order = 1;
options_.periods = 0;
var_list_ = char('lnN1t','lnN2t','lnTotHours1','lnTotHours2','lnV1t','lnV2t','lnIc1t','lnIc2t','lnYb1t','lnYb2t','lnCc1t','lnCc2t','LabShare1','LabShare2');
info = stoch_simul(var_list_);
save('dmp_2c_xu_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('dmp_2c_xu_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('dmp_2c_xu_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('dmp_2c_xu_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('dmp_2c_xu_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('dmp_2c_xu_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('dmp_2c_xu_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
